---
# tasks file for app

- name: Install nginx
  apt:
    name: nginx
    state: latest
- name: Start nginx
  service:
    name: nginx
    state: started
- name: Install tomcat
  apt:
    name: tomcat9
    state: latest
- name: Starting tomcat
  service:
    name: tomcat9
    state: started
- name: Install mysql
  apt:
    name: "{{ item }}"
  with_items:
    - python-mysqldb
    - mysql-server
- name: Create mysql database
  mysql_db:
    name: test_db
    state: present
- name: Create mysql user
  mysql_user:
    name={{ user_name }}
    password={{ user_pass }}
    priv=*.*:ALL
